// Proyección compartida para colas operativas. Las vistas de lista necesitan
// estos campos para filtros, tarjetas, acciones y el detalle existente; los
// blobs/arrays legacy se cargan solo cuando el flujo de detalle los requiere.
export const OPERATIONAL_ORDER_COLUMNS = [
  "id",
  "client_id",
  "client_name",
  "client_contact",
  "description",
  "material",
  "size",
  "quantity",
  "price",
  "status",
  "payment_status",
  "created_at",
  "updated_at",
  "created_by",
  "seller_id",
  "designer_id",
  "quote_id",
  "production_id",
  "delivery_id",
  "order_type",
  "order_design_type",
  "termination_type",
  "delivery_date",
  "invoice_number",
  "invoice_assignment_mode",
  "invoice_payment",
  "preview_image",
  "order_file_url",
  "reference_images",
  "return_reason",
  "returned_to_designer_at",
  "cancellation_reason",
  "is_archived",
  "is_archived_designer",
  "is_archived_quote",
  "is_archived_admin",
  "is_archived_production",
  "is_archived_delivery",
  "tracking_token",
  "operational_status",
  "blocked_reason_category",
  "blocked_reason_detail",
  "blocked_owner_id",
  "blocked_at",
  "blocked_expected_resolution_at",
  "commercial_review_required",
  "delivered_at",
  "delivery_note",
].join(",");

export const PRODUCTION_ORDER_SELECT = [
  OPERATIONAL_ORDER_COLUMNS,
  "order_production_files(id,order_id,url,filename,production_area_code,status,assigned_to,created_by,updated_by,started_at,in_termination_at,completed_at,created_at,updated_at,public_label,order_file_id,material_names,termination_name)",
  "order_production_assignments(id,order_id,production_area_code,assigned_to,assigned_by,created_at,updated_at)",
  "order_production_user_archives(order_id,user_id,archived_at)",
].join(",");

export const QUOTE_ORDER_SELECT = [
  OPERATIONAL_ORDER_COLUMNS,
  "order_production_files(id,order_id,url,filename,public_label,production_area_code,material_names,termination_name,status,updated_at)",
].join(",");
